//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Web.HealthFoot.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class AspNetDirectorio
    {
        public string Id { get; set; }
        public string Titular { get; set; }
        public string Pais { get; set; }
        public string Estado { get; set; }
        public string Ciudad { get; set; }
        public string Calle { get; set; }
        public string CP { get; set; }
        public string Referencia { get; set; }
        public string Telefono { get; set; }
        public Nullable<int> Status { get; set; }
        public string IdUs { get; set; }
    }
}
