// <auto-generated />
namespace Web.HealthFoot.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class ColumnasUserLA2 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(ColumnasUserLA2));
        
        string IMigrationMetadata.Id
        {
            get { return "201911200328526_ColumnasUserLA2"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
